data:
  river_data_path: "data/river_data/ea_gauge_data"
  weather_data_path: "data/weather_data/"
  merged_data_path: "data/river_weather_merged_data/"
  frequency: "15min"

preprocessing:
  outlier_std_threshold: 10
  imputation_method: "seasonal"
  negative_values: "replace_nan"

features:
  lag_hours: [1, 3, 6, 12, 24]
  rolling_windows: [3, 6, 12]
  weather_features:
    - temp
    - dwpt
    - rhum
    - prcp
    - wdir
    - wspd
    - wpgt

models:
  random_forest:
    n_estimators: 100
    random_state: 42
    test_size: 0.2
    
  arima:
    seasonal: True
    m: 96  # For 15-minute data, 96 periods per day
    
visualization:
  style: "seaborn"
  figure_size: [12, 8]
  save_path: "assets/"
