defaults: &defaults
  test_size: 168  # 1 week of hourly data
  train_val_split: 0.8
  random_state: 42
  target_column: 'value'

arima:
  order: [1, 1, 1]
  seasonal_order: [1, 1, 1, 24]

xgboost:
  max_depth: 6
  learning_rate: 0.1
  n_estimators: 100
  objective: 'reg:squarederror'
  early_stopping_rounds: 10
  verbosity: 1

catboost:
  iterations: 1000
  learning_rate: 0.1
  depth: 6
  loss_function: 'RMSE'
  early_stopping_rounds: 10
  verbose: 100

lstm:
  hidden_size: 64
  num_layers: 2
  dropout: 0.1
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  sequence_length: 24  # Look back 24 hours

transformer:
  d_model: 64
  nhead: 8
  num_encoder_layers: 3
  dim_feedforward: 256
  dropout: 0.1
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  sequence_length: 168  # Look back 1 week
